FROM ubuntu

RUN \
    apt update && \
    apt upgrade -y && \
    apt install -y \
    curl git cmake clang gdb default-jre \
    libboost-all-dev catch2 \
    llvm libzstd-dev libedit-dev libcurlpp-dev libomp-dev libpolly-18-dev libpfm4-dev